# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#format = '''
#$kubernetes $aws $python
#$directory $git_branch 
#[](fg:#8CF392 bg:#030B16) $character
#'''

# Move the directory to the second line
#format = '$all$directory$character$hostname'
#format = '$all$hostname$username$localip'

continuation_prompt = '▶▶ '

# Inserts a blank line between shell prompts
add_newline = false

# ~/.config/starship.toml

[hostname]
ssh_only = false
#detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
#disabled = false

# ~/.config/starship.toml

[directory]
truncation_length = 8
truncation_symbol = '…/'

